# Generated by Django 4.1.3 on 2022-12-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_attributetype_attributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='images',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
