# Generated by Django 4.1.3 on 2022-12-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_attributevalue_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.attributetype'),
        ),
    ]
