# Generated by Django 4.1.3 on 2022-12-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variations',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='forProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='products.product'),
        ),
    ]
