# Generated by Django 4.1.3 on 2022-12-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_variations_attributevalue_forproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='atrib',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='forProduct',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='foratr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.attributetype'),
        ),
    ]
