# Generated by Django 4.1.3 on 2023-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='color_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
